In [42]:
import numpy as np
a = np.array([1, 2, 3]).reshape(1, -1)
x = np.array([1, 6, 9]).reshape(-1, 1)
print('vector_a : ', a)
print('vector_x : \n', x)

vector_a :  [[1 2 3]]
vector_x : 
 [[1]
 [6]
 [9]]


In [43]:
res = a.dot(x)
print('a dot x : ', res)

a dot x :  [[40]]


In [44]:
A = np.array([i for i in range(1, 10)]).reshape(3, 3)
x = np.array([1, 6, 9]).reshape(-1, 1)
A, x

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1],
        [6],
        [9]]))

In [45]:
res = A.dot(x)
res

array([[ 40],
       [ 88],
       [136]])

In [46]:
A = np.array([i for i in range(1, 10)]).reshape(3, 3)
X = np.array([1, 6, 9]*6).reshape(3, 6)
A, X

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 6, 9, 1, 6, 9],
        [1, 6, 9, 1, 6, 9],
        [1, 6, 9, 1, 6, 9]]))

In [47]:
A = np.array([
    [1/np.sqrt(2), 1/np.sqrt(2), 0],
    [1/np.sqrt(2), -1/np.sqrt(2), 0],
    [0, 0, 1]
])

X = np.array([
    [np.sqrt(2), 2*np.sqrt(2), np.sqrt(2), 2*np.sqrt(2)],
    [np.sqrt(2), 2*np.sqrt(2), np.sqrt(2), 2*np.sqrt(2)],
    [1, 1, 1, 1]
])

A, X

(array([[ 0.70710678,  0.70710678,  0.        ],
        [ 0.70710678, -0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[1.41421356, 2.82842712, 1.41421356, 2.82842712],
        [1.41421356, 2.82842712, 1.41421356, 2.82842712],
        [1.        , 1.        , 1.        , 1.        ]]))

In [48]:
# 验证矩阵 A 的每个行向量都是单位向量
A[0].dot(A[0].T), A[1].dot(A[1].T), A[2].dot(A[2].T)

(0.9999999999999998, 0.9999999999999998, 1.0)

In [50]:
# 验证矩阵 A 的任意两个行向量都是正交的
A[0].dot(A[1].T), A[0].dot(A[2].T), A[1].dot(A[2].T)

(0.0, 0.0, 0.0)

In [51]:
# 计算 A 点乘 X
A.dot(X)

array([[2.00000000e+00, 4.00000000e+00, 2.00000000e+00, 4.00000000e+00],
       [2.02930727e-17, 4.05861454e-17, 2.02930727e-17, 4.05861454e-17],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])